services:
  web:
    build:
      context: .
      dockerfile: .docker/web.dockerfile
    image: docker-drupal-api:latest
    ports:
      - 80:80
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - code:/opt/drupal/code:delegated
      - files:/opt/drupal/web/sites/default/files:delegated
      - ./config/:/opt/drupal/config:delegated
      - ./settings.php:/opt/drupal/web/sites/default/settings.php:ro

  cron:
    build:
      context: .
      dockerfile: .docker/crontab.dockerfile
    links:
      - mysql
    depends_on:
      - mysql
      - web
    volumes:
      - code:/opt/drupal/code:delegated
      - files:/opt/drupal/web/sites/default/files:delegated
      - ./settings.php:/opt/drupal/web/sites/default/settings.php:ro

  mysql:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command:
      - "--max-allowed-packet=64M"
      - "--innodb-buffer-pool-size=2750M"
      - "--innodb-buffer-pool-instances=2"
      - "--innodb-log-file-size=256M"
      - "--tmp-table-size=32M"
      - "--join-buffer-size=1M"
      - "--transaction-isolation=READ-COMMITTED"
    volumes:
      - "mysql:/var/lib/mysql:delegated"

volumes:
  mysql: null
  files: null
  code: null
