version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: .docker/web.dockerfile
    image: docker-drupal-api:latest
    ports:
      - 80:80
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - code:/var/www/html/code:delegated
      - sites:/var/www/html/sites:delegated

  cron:
    build:
      context: .
      dockerfile: .docker/crontab.dockerfile
    links:
      - mysql
    depends_on:
      - mysql
      - web
    volumes:
      - code:/var/www/html/code:ro
      - sites:/var/www/html/sites:ro

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
    command:
      - "--max_allowed_packet=64M"
    volumes:
      - "mysql:/var/lib/mysql:delegated"

volumes:
  mysql: null
  code: null
  sites: null